import type { CountryPhoneCode, PartnerCategory } from "@/types/partners";

// Real partner directory data lives in the backend (PartnersController) —
// approved partners flow straight onto /OurPartners, and the same records
// back /admin/partners.
export const PARTNER_CATEGORIES: PartnerCategory[] = ["eventPlanner", "photographer", "designer", "other"];

// Full country list for the "Apply Now" form — much broader than the six
// countries partners currently operate from, since applicants can be
// anywhere. Sorted A-Z so it's fast to scan; "Other" is a catch-all, not a
// real country, so it stays pinned at the end instead of being sorted in.
const APPLICATION_COUNTRIES_SORTED = [
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "China",
  "Denmark",
  "Egypt",
  "Ethiopia",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "India",
  "Indonesia",
  "Iraq",
  "Israel",
  "Italy",
  "Japan",
  "Jordan",
  "Kenya",
  "Kuwait",
  "Lebanon",
  "Libya",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sudan",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tunisia",
  "Turkey",
  "UAE",
  "United Kingdom",
  "United States",
  "Yemen",
];

export const APPLICATION_COUNTRIES = [...APPLICATION_COUNTRIES_SORTED, "Other"];

// Same country set as APPLICATION_COUNTRIES (minus the "Other" catch-all,
// which has no dial code), sorted A-Z to match the country selector above.
export const PHONE_CODES: CountryPhoneCode[] = [
  { country: "Algeria", flag: "🇩🇿", code: "+213", iso: "DZ" },
  { country: "Argentina", flag: "🇦🇷", code: "+54", iso: "AR" },
  { country: "Australia", flag: "🇦🇺", code: "+61", iso: "AU" },
  { country: "Austria", flag: "🇦🇹", code: "+43", iso: "AT" },
  { country: "Bahrain", flag: "🇧🇭", code: "+973", iso: "BH" },
  { country: "Bangladesh", flag: "🇧🇩", code: "+880", iso: "BD" },
  { country: "Belgium", flag: "🇧🇪", code: "+32", iso: "BE" },
  { country: "Brazil", flag: "🇧🇷", code: "+55", iso: "BR" },
  { country: "Canada", flag: "🇨🇦", code: "+1", iso: "CA" },
  { country: "China", flag: "🇨🇳", code: "+86", iso: "CN" },
  { country: "Denmark", flag: "🇩🇰", code: "+45", iso: "DK" },
  { country: "Egypt", flag: "🇪🇬", code: "+20", iso: "EG" },
  { country: "Ethiopia", flag: "🇪🇹", code: "+251", iso: "ET" },
  { country: "France", flag: "🇫🇷", code: "+33", iso: "FR" },
  { country: "Germany", flag: "🇩🇪", code: "+49", iso: "DE" },
  { country: "Ghana", flag: "🇬🇭", code: "+233", iso: "GH" },
  { country: "Greece", flag: "🇬🇷", code: "+30", iso: "GR" },
  { country: "India", flag: "🇮🇳", code: "+91", iso: "IN" },
  { country: "Indonesia", flag: "🇮🇩", code: "+62", iso: "ID" },
  { country: "Iraq", flag: "🇮🇶", code: "+964", iso: "IQ" },
  { country: "Israel", flag: "🇮🇱", code: "+972", iso: "IL" },
  { country: "Italy", flag: "🇮🇹", code: "+39", iso: "IT" },
  { country: "Japan", flag: "🇯🇵", code: "+81", iso: "JP" },
  { country: "Jordan", flag: "🇯🇴", code: "+962", iso: "JO" },
  { country: "Kenya", flag: "🇰🇪", code: "+254", iso: "KE" },
  { country: "Kuwait", flag: "🇰🇼", code: "+965", iso: "KW" },
  { country: "Lebanon", flag: "🇱🇧", code: "+961", iso: "LB" },
  { country: "Libya", flag: "🇱🇾", code: "+218", iso: "LY" },
  { country: "Malaysia", flag: "🇲🇾", code: "+60", iso: "MY" },
  { country: "Mexico", flag: "🇲🇽", code: "+52", iso: "MX" },
  { country: "Morocco", flag: "🇲🇦", code: "+212", iso: "MA" },
  { country: "Netherlands", flag: "🇳🇱", code: "+31", iso: "NL" },
  { country: "New Zealand", flag: "🇳🇿", code: "+64", iso: "NZ" },
  { country: "Nigeria", flag: "🇳🇬", code: "+234", iso: "NG" },
  { country: "Norway", flag: "🇳🇴", code: "+47", iso: "NO" },
  { country: "Oman", flag: "🇴🇲", code: "+968", iso: "OM" },
  { country: "Pakistan", flag: "🇵🇰", code: "+92", iso: "PK" },
  { country: "Palestine", flag: "🇵🇸", code: "+970", iso: "PS" },
  { country: "Philippines", flag: "🇵🇭", code: "+63", iso: "PH" },
  { country: "Poland", flag: "🇵🇱", code: "+48", iso: "PL" },
  { country: "Portugal", flag: "🇵🇹", code: "+351", iso: "PT" },
  { country: "Qatar", flag: "🇶🇦", code: "+974", iso: "QA" },
  { country: "Romania", flag: "🇷🇴", code: "+40", iso: "RO" },
  { country: "Saudi Arabia", flag: "🇸🇦", code: "+966", iso: "SA" },
  { country: "Singapore", flag: "🇸🇬", code: "+65", iso: "SG" },
  { country: "South Africa", flag: "🇿🇦", code: "+27", iso: "ZA" },
  { country: "South Korea", flag: "🇰🇷", code: "+82", iso: "KR" },
  { country: "Spain", flag: "🇪🇸", code: "+34", iso: "ES" },
  { country: "Sudan", flag: "🇸🇩", code: "+249", iso: "SD" },
  { country: "Sweden", flag: "🇸🇪", code: "+46", iso: "SE" },
  { country: "Switzerland", flag: "🇨🇭", code: "+41", iso: "CH" },
  { country: "Syria", flag: "🇸🇾", code: "+963", iso: "SY" },
  { country: "Tunisia", flag: "🇹🇳", code: "+216", iso: "TN" },
  { country: "Turkey", flag: "🇹🇷", code: "+90", iso: "TR" },
  { country: "UAE", flag: "🇦🇪", code: "+971", iso: "AE" },
  { country: "United Kingdom", flag: "🇬🇧", code: "+44", iso: "GB" },
  { country: "United States", flag: "🇺🇸", code: "+1", iso: "US" },
  { country: "Yemen", flag: "🇾🇪", code: "+967", iso: "YE" },
];
