// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Numinds.Api.Data;

#nullable disable

namespace Numinds.Api.Migrations
{
    [DbContext(typeof(NumindsDbContext))]
    [Migration("20260802145853_AddNonWeddingCategoryTemplates")]
    partial class AddNonWeddingCategoryTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccommodationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableGifts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableQrEntry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRsvp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvelopeNameFont")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventRulesText")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTitleFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName1")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName2")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyNamesFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralTextFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftIban")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideCameraButton")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideCapturedGallery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideFamilyNames")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideSaveButton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvitationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoupleEvent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamesFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("OccasionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalMessageSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalMessageText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalMessageTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RsvpShowAttendance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RsvpShowGuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RsvpShowLiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RsvpShowMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAccommodation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowEventProgram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowEventRules")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPersonalMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThankYouText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThankYouTextColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseHijriDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseNameImage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.RsvpResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Attending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.ToTable("RsvpResponses");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmbientEffect")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBg")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecorationImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultNamesFont")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroIllustrationUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageBg")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryAccent")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColor")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000001"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1673026190548-c95adc90ef60?w=1200&q=80",
                            CardBg = "#fbeee5",
                            Category = "wedding",
                            Code = "W024",
                            DefaultNamesFont = "font-cinzel",
                            ImageUrl = "https://images.unsplash.com/photo-1673026190548-c95adc90ef60?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#faf1ea,#fffdfa",
                            PrimaryAccent = "#8c2a3a",
                            TextColor = "#5c1a26"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000002"),
                            AmbientEffect = "smoke",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1762621175799-5fc1e336e84a?w=1200&q=80",
                            CardBg = "#2b2119",
                            Category = "wedding",
                            Code = "W031",
                            DefaultNamesFont = "font-cinzel",
                            ImageUrl = "https://images.unsplash.com/photo-1762621175799-5fc1e336e84a?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#241d17,#332920",
                            PrimaryAccent = "#D8C4A0",
                            TextColor = "#F3E9DC"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000003"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1526353043579-c836f1c675ad?w=1200&q=80",
                            CardBg = "#fdf3e4",
                            Category = "wedding",
                            Code = "W029",
                            DefaultNamesFont = "font-serif",
                            ImageUrl = "https://images.unsplash.com/photo-1526353043579-c836f1c675ad?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#fdf6ec,#fffcf5",
                            PrimaryAccent = "#c98a5a",
                            TextColor = "#6b4a2f"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000004"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1584032910793-7aa893dbefda?w=1200&q=80",
                            CardBg = "#ffffff",
                            Category = "wedding",
                            Code = "W019",
                            DefaultNamesFont = "italic font-serif",
                            ImageUrl = "https://images.unsplash.com/photo-1584032910793-7aa893dbefda?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#ffffff,#fbfbf9",
                            PrimaryAccent = "#a68a4a",
                            TextColor = "#5a5a54"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000005"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=1200&q=80",
                            CardBg = "#0f2419",
                            Category = "wedding",
                            Code = "W101",
                            ImageUrl = "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#0b1f16,#16291e",
                            PrimaryAccent = "#8FBF9F",
                            TextColor = "#DCEBD9"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000006"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
                            CardBg = "#fffaf2",
                            Category = "wedding",
                            Code = "W102",
                            ImageUrl = "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
                            IsPopular = false,
                            Layout = "boxed-hero",
                            PageBg = "#fbf3e7,#fff9f0",
                            PrimaryAccent = "#b8823c",
                            TextColor = "#4a3520"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000007"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1778186414142-7e4100e9f17d?w=1200&q=80",
                            CardBg = "#fff5f7",
                            Category = "wedding",
                            Code = "W103",
                            ImageUrl = "https://images.unsplash.com/photo-1778186414142-7e4100e9f17d?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#fdf2f4,#fffbfc",
                            PrimaryAccent = "#c9748a",
                            TextColor = "#6b2f3a"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000008"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1686538246844-f3ca82434d95?w=1200&q=80",
                            CardBg = "#fbeee0",
                            Category = "engagement",
                            Code = "E001",
                            ImageUrl = "https://images.unsplash.com/photo-1686538246844-f3ca82434d95?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#fdf3ea,#fffaf5",
                            PrimaryAccent = "#c9945a",
                            TextColor = "#7a4a35"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000009"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1639078007551-b14a57d62c8d?w=1200&q=80",
                            CardBg = "#f7f4ef",
                            Category = "engagement",
                            Code = "E002",
                            ImageUrl = "https://images.unsplash.com/photo-1639078007551-b14a57d62c8d?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#f3efe9,#fdfdfb",
                            PrimaryAccent = "#a89a86",
                            TextColor = "#5a5652"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-00000000000a"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1596911942922-521ec0db907d?w=1200&q=80",
                            CardBg = "#f7efd9",
                            Category = "marriage_contract",
                            Code = "Q001",
                            DefaultNamesFont = "font-cinzel",
                            ImageUrl = "https://images.unsplash.com/photo-1596911942922-521ec0db907d?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#faf5e8,#fffdf7",
                            PrimaryAccent = "#b8963c",
                            TextColor = "#5c4a1f"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-00000000000b"),
                            AmbientEffect = "smoke",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1730376475964-0e196eb95a6e?w=1200&q=80",
                            CardBg = "#16203a",
                            Category = "marriage_contract",
                            Code = "Q002",
                            DefaultNamesFont = "font-cinzel",
                            ImageUrl = "https://images.unsplash.com/photo-1730376475964-0e196eb95a6e?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#111a2e,#1c2740",
                            PrimaryAccent = "#c9a13c",
                            TextColor = "#e8d9a8"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-00000000000c"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1771992230505-97e0c3d38213?w=1200&q=80",
                            CardBg = "#fde2c8",
                            Category = "henna",
                            Code = "H001",
                            ImageUrl = "https://images.unsplash.com/photo-1771992230505-97e0c3d38213?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#fdece0,#fff8f0",
                            PrimaryAccent = "#d9741f",
                            TextColor = "#7a3a1a"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-00000000000d"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1771992228898-79342c9c1c39?w=1200&q=80",
                            CardBg = "#fbd9c4",
                            Category = "henna",
                            Code = "H002",
                            ImageUrl = "https://images.unsplash.com/photo-1771992228898-79342c9c1c39?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#fbe4d8,#fff6f0",
                            PrimaryAccent = "#c0392b",
                            TextColor = "#6b2a1a"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-00000000000e"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1727178757622-26389a0538f5?w=1200&q=80",
                            CardBg = "#fbe4e8",
                            Category = "bridal_shower",
                            Code = "S001",
                            ImageUrl = "https://images.unsplash.com/photo-1727178757622-26389a0538f5?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#fdf1f3,#fffbfc",
                            PrimaryAccent = "#d88a9e",
                            TextColor = "#8a3f52"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-00000000000f"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1581022295432-7fabcc628434?w=1200&q=80",
                            CardBg = "#f9dee6",
                            Category = "bridal_shower",
                            Code = "S002",
                            ImageUrl = "https://images.unsplash.com/photo-1581022295432-7fabcc628434?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#fbeaf0,#fff8fa",
                            PrimaryAccent = "#e0a0b8",
                            TextColor = "#7a3f52"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000010"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1768776181652-d640d88a75f0?w=1200&q=80",
                            CardBg = "#e8e5f5",
                            Category = "gender_reveal",
                            Code = "R001",
                            ImageUrl = "https://images.unsplash.com/photo-1768776181652-d640d88a75f0?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#f0eef7,#fbfaff",
                            PrimaryAccent = "#9b8fc9",
                            TextColor = "#4a4568"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000011"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1560128411-79892dd93bf8?w=1200&q=80",
                            CardBg = "#dcebfa",
                            Category = "gender_reveal",
                            Code = "R002",
                            ImageUrl = "https://images.unsplash.com/photo-1560128411-79892dd93bf8?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#eaf2fb,#f8fbff",
                            PrimaryAccent = "#7fa8d9",
                            TextColor = "#2f4a68"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000012"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1704649917979-9a23d585da95?w=1200&q=80",
                            CardBg = "#f5eee0",
                            Category = "aqeeqah",
                            Code = "A001",
                            ImageUrl = "https://images.unsplash.com/photo-1704649917979-9a23d585da95?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#faf6ee,#fffdf8",
                            PrimaryAccent = "#c9b183",
                            TextColor = "#6b5a3f"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000013"),
                            AmbientEffect = "petals",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1741840800730-785888bd32c2?w=1200&q=80",
                            CardBg = "#f7dee2",
                            Category = "aqeeqah",
                            Code = "A002",
                            ImageUrl = "https://images.unsplash.com/photo-1741840800730-785888bd32c2?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#fbeef0,#fff9fa",
                            PrimaryAccent = "#d98fa0",
                            TextColor = "#7a4a52"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000014"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1636231945376-3d40fdcbc462?w=1200&q=80",
                            CardBg = "#13291f",
                            Category = "graduation",
                            Code = "G001",
                            ImageUrl = "https://images.unsplash.com/photo-1636231945376-3d40fdcbc462?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#0f1f18,#182e24",
                            PrimaryAccent = "#5fae7f",
                            TextColor = "#dcece0"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000015"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1785052335573-8c0bcd811c5b?w=1200&q=80",
                            CardBg = "#f7ecc4",
                            Category = "graduation",
                            Code = "G002",
                            ImageUrl = "https://images.unsplash.com/photo-1785052335573-8c0bcd811c5b?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#fdf6e3,#fffcf0",
                            PrimaryAccent = "#c9a227",
                            TextColor = "#6b5518"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000016"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1762918988304-97d4a5840a4a?w=1200&q=80",
                            CardBg = "#f7ead0",
                            Category = "birthday",
                            Code = "B001",
                            ImageUrl = "https://images.unsplash.com/photo-1762918988304-97d4a5840a4a?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed",
                            PageBg = "#fbf3e6,#fffcf5",
                            PrimaryAccent = "#c9a13c",
                            TextColor = "#6b5220"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000017"),
                            AmbientEffect = "sparkle",
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1780586382191-bef9c740798e?w=1200&q=80",
                            CardBg = "#dff0e3",
                            Category = "birthday",
                            Code = "B002",
                            ImageUrl = "https://images.unsplash.com/photo-1780586382191-bef9c740798e?w=800&q=80",
                            IsPopular = false,
                            Layout = "full-bleed",
                            PageBg = "#eef7f0,#fbfffb",
                            PrimaryAccent = "#7fbf95",
                            TextColor = "#2f5240"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Invitation", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.Template", "Template")
                        .WithMany("Invitations")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.RsvpResponse", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.Invitation", "Invitation")
                        .WithMany("Responses")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Invitation", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Template", b =>
                {
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
