// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Numinds.Api.Data;

#nullable disable

namespace Numinds.Api.Migrations
{
    [DbContext(typeof(NumindsDbContext))]
    [Migration("20260801152718_AddTemplateLayoutFields")]
    partial class AddTemplateLayoutFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccommodationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableGifts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableQrEntry")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRsvp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvelopeNameFont")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventRulesText")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTitleFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName1")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName2")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyNamesFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GalleryImagesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralTextFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiftIban")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideCameraButton")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideCapturedGallery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideFamilyNames")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HideSaveButton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvitationText")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoupleEvent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamesFont")
                        .HasColumnType("TEXT");

                    b.Property<string>("OccasionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalMessageSignature")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalMessageText")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalMessageTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RsvpShowAttendance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RsvpShowGuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RsvpShowLiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RsvpShowMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAccommodation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowEventProgram")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowEventRules")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPersonalMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThankYouText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThankYouTextColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseHijriDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseNameImage")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.RsvpResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Attending")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId");

                    b.ToTable("RsvpResponses");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000001"),
                            Category = "wedding",
                            Code = "W024",
                            ImageUrl = "/images/templates/w024.png",
                            IsPopular = true,
                            Layout = "none"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000002"),
                            Category = "wedding",
                            Code = "W031",
                            ImageUrl = "/images/templates/w031.jpeg",
                            IsPopular = false,
                            Layout = "none"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000003"),
                            Category = "wedding",
                            Code = "W029",
                            ImageUrl = "/images/templates/w029.png",
                            IsPopular = false,
                            Layout = "none"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000004"),
                            Category = "wedding",
                            Code = "W019",
                            ImageUrl = "/images/templates/w019.png",
                            IsPopular = false,
                            Layout = "none"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000005"),
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=1200&q=80",
                            Category = "wedding",
                            Code = "W101",
                            ImageUrl = "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=800&q=80",
                            IsPopular = true,
                            Layout = "full-bleed"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000006"),
                            BackgroundImageUrl = "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80",
                            Category = "wedding",
                            Code = "W102",
                            ImageUrl = "https://images.unsplash.com/photo-1519741497674-611481863552?w=800&q=80",
                            IsPopular = false,
                            Layout = "boxed-hero"
                        },
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-adb2-000000000007"),
                            Category = "wedding",
                            Code = "W103",
                            ImageUrl = "/images/templates/w029.png",
                            IsPopular = false,
                            Layout = "overlay"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Invitation", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.Template", "Template")
                        .WithMany("Invitations")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Numinds.Api.Models.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.RsvpResponse", b =>
                {
                    b.HasOne("Numinds.Api.Models.Entities.Invitation", "Invitation")
                        .WithMany("Responses")
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Invitation", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Numinds.Api.Models.Entities.Template", b =>
                {
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
